services:
  - type: web
    name: dysco-expo-tunnel
    env: docker
    dockerfilePath: ./apps/mobile/Dockerfile
    dockerContext: ./apps/mobile
    plan: starter
    buildCommand: ""
    startCommand: "/start.sh"
    envVars:
      - key: CI
        value: "1"
      - key: PORT
        value: "8081"
    autoDeploy: true